sparse matrix를 모조리 메모리 상에 올려놓는 것... 너무 비효율적이고 메모리 낭비임.  
sparse matrix를 사용해서 좀 줄여보자.

- COO(coordinat)형식
- CSR(Compressed Sparse Row)형식
  - np.array(값, 행, 열)

In [14]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt # https://matplotlib.org/stable/api/pyplot_summary.html#module-matplotlib.pyplot

In [12]:
ratings = {
    "user_id": [1, 2, 4],
    "movie_id": [2, 3, 7],
    "rating": [4, 3, 1]
}
ratings = pd.DataFrame(ratings)
rating_matrix = ratings.pivot_table(index="user_id",
                                    columns="movie_id",
                                    values="rating"
    ).fillna(0)

rating_matrix

movie_id    2    3    7
user_id                
1         4.0  0.0  0.0
2         0.0  3.0  0.0
4         0.0  0.0  1.0

In [13]:
full_matrix1 = np.array(rating_matrix)
full_matrix1

array([[4., 0., 0.],
       [0., 3., 0.],
       [0., 0., 1.]])

## csr_matrix

In [18]:
from scipy.sparse import csr_matrix

data = np.array(ratings["rating"])
row_indices = np.array(ratings["user_id"])
col_indices = np.array(ratings["movie_id"])

rating_matrix = csr_matrix((data, (row_indices, col_indices)), dtype=int)

# (1, 2)	4
# (2, 3)	3
# (4, 7)	1
print(rating_matrix)

# <5x8 sparse matrix of type '<class 'numpy.int64'>'
# 	with 3 stored elements in Compressed Sparse Row format>
rating_matrix

  (1, 2)	4
  (2, 3)	3
  (4, 7)	1


<5x8 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [19]:
# csr matrix를 full matrix로 변환
full_matrix2 = rating_matrix.toarray()
print(full_matrix2)

[[0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
