# Pytorch basics for DL newbies


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/BoostcampAITech/lecture-note-python-basics-for-ai/blob/main/codes/pytorch/07_torch-study/torch_basics.ipynb)


## numpy to tensor

In [1]:
import numpy as np

n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [2]:
import torch

t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [3]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


### Array to Tensor

##### Data to tensor

In [4]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

##### ndArray to Tensor

In [5]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### numpy like operations

In [6]:
data = [
    [3, 5, 20],
    [10, 5, 50], 
    [1, 5, 10]]
x_data = torch.tensor(data)

In [7]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [8]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [9]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [10]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [11]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [12]:
x_data.shape

torch.Size([3, 3])

In [13]:
x_data.dtype

torch.int64

In [14]:
x_data.device

device(type='cpu')

In [15]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

NameError: name 'x_data_cuda' is not defined

### Tensor handling

In [16]:
tensor_ex = torch.rand(size=(2, 3, 2)) # (3, 2)가 2겹 있다
tensor_ex

tensor([[[0.5188, 0.2105],
         [0.0014, 0.1550],
         [0.1406, 0.8533]],

        [[0.1361, 0.4566],
         [0.5249, 0.0491],
         [0.9826, 0.8314]]])

In [17]:
tensor_ex.view([-1, 6])

tensor([[0.5188, 0.2105, 0.0014, 0.1550, 0.1406, 0.8533],
        [0.1361, 0.4566, 0.5249, 0.0491, 0.9826, 0.8314]])

In [18]:
tensor_ex.reshape([-1,6])

tensor([[0.5188, 0.2105, 0.0014, 0.1550, 0.1406, 0.8533],
        [0.1361, 0.4566, 0.5249, 0.0491, 0.9826, 0.8314]])

In [19]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
a

In [ ]:
b

In [ ]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

In [ ]:
a

In [ ]:
b

In [ ]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()

In [ ]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape

In [ ]:
tensor_ex.unsqueeze(1).shape

In [ ]:
tensor_ex.unsqueeze(2).shape

## tensor operations

In [ ]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

In [ ]:
t1 - t1

In [ ]:
t1 + 10

In [ ]:
t1 + t2

In [ ]:
t1 - t1

In [ ]:
t1 + 10

In [ ]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

In [ ]:
t1.dot(t2)

In [ ]:
t1.matmul(t2)


In [ ]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

In [ ]:
a

In [ ]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

In [ ]:
t1.dot(t2)

In [ ]:
t1.matmul(t2)

In [22]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(2.6183)

In [23]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: self must be a matrix

In [24]:
a = torch.rand(5,2, 3)
b = torch.rand(5)
a.mm(b)

RuntimeError: self must be a matrix

In [ ]:
a = torch.rand(5,2, 3)
b = torch.rand(3)
a.matmul(b)

In [ ]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()



In [ ]:
a[1].mm(torch.unsqueeze(b,1))


In [ ]:
a[2].mm(torch.unsqueeze(b,1))


In [ ]:
a[3].mm(torch.unsqueeze(b,1))


In [ ]:
a[4].mm(torch.unsqueeze(b,1))


## tensor operations for ML/DL formula

In [ ]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor


In [ ]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)

y_label

In [ ]:
torch.nn.functional.one_hot(y_label)

In [ ]:
torch.nn.functional.one_hot(y_label)


In [ ]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))

In [ ]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

## torch autogard

$$
y = w^2 \\ 
z = 10*y + 25 \\
z = 10*w^2 + 25 
$$

In [ ]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 50
z.backward()
w.grad

In [ ]:
w.grad

$$ Q = 3a^3 - b^2  $$

In [ ]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad 

In [ ]:
b.grad

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$

In [ ]:
a.grad

In [ ]:
b.grad